name: BetterAntiSwear
main: me.BetterAntiSwear.BetterAntiSwear
authors: [brooky1010, Neonix#1337]
softdepend: [Vault, HologramAPI]
version: 1.2
api-version: 1.16

commands:
  antiswear:
    usage: /<command> [message|prefix|info|kickmessage|add|remove|toggle|cc|debug|check|help|count] [argument]
    description: Manages the antiswear plugin.
    aliases: [as, asw]
   
permissions:
  antiswear.*:
    description: Gives access to all the permissions.
    children:
      antiswear.reload: true
      antiswear.manage: true
      antiswear.bypass: true
      antiswear.toggle: true
      antiswear.mod: true
      antiswear.cc: true
    default: op

  antiswear.reload:
    description: Reload the BetterAntiSwear config.
    default: op
   
  antiswear.manage:
    description: Manages the messages.
    default: op
   
  antiswear.bypass:
    description: Be able to talk when the chat is muted.
    default: op
   
  antiswear.toggle:
    description: Be able toggle between global mute and unmute.
    default: op  
   
  antiswear.mod:
    description: Receive the message if players tried to swear.
    default: op  